import type { TrainingWeek } from '../../types/training';

const block1Week7: TrainingWeek = {
  id: 'block-1-week-7',
  block: 1,
  week: 7,
  title: 'Skill Consolidation + Technical Capacity',
  description:
    'Squat Catch korunurken Snatch pull-under zamanlamasını erkene alma, Clean teknik kalitesini yük altında koruma, Butterfly quality + rep gelişimi, gerçek Double Under benchmark, tam ROM Strict Pull-up, squat strength progression ve running capacity. Hedef haftalık RPE 7–8. Olympic teknik kalite yükten öncelikli. Failure yok. Accessory ve Day D opsiyonel. Sandbag yok.',

  days: [
    {
      id: 'block-1-week-7-day-a',
      day: 'DAY A',
      title: 'Snatch + Butterfly Quality/Capacity',
      duration: '80–90 dk',
      focus:
        'Squat Snatch · Pull-Under Timing · Butterfly Quality/Capacity · Back Squat · Running',
      purpose:
        'Squat Catch kazanımını korurken pull-under zamanlamasını erkene almak, Butterfly’da kalite ve tekrar sayısını birlikte geliştirmek ve running stimulusunu tekrar uygulamak.',
      sections: [
        {
          id: 'w7-a-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            '2 tur',
            '200 m Row',
            '8 Walking Lunge',
            '10 Air Squat',
            '10 Scap Pull-Up',
            '8 PVC OHS',
            '8 PVC Snatch',
            'Empty Bar: 5 Snatch Grip RDL',
            '5 Muscle Snatch',
            '5 Tall Snatch',
            '5 High-Hang Squat Snatch',
            '5 OHS',
          ],
        },
        {
          id: 'w7-a-olympic-drill',
          title: 'Olympic Drill',
          duration: '15 dk',
          items: [
            'Tall Snatch — 4×2 @30 kg',
            'Her tekrar arasında 3–5 sn reset',
            'Amaç: Barı gereğinden fazla yukarı çekmek yerine barın altına hızlanmak.',
            'High-Hang Squat Snatch — 3×2 @35–40 kg',
            'Amaç: Extension → Immediate Pull-Under → Active Squat Catch',
            'Snatch Balance — 2×2 @40 kg',
            'Amaç: Aggressive lockout + Overhead confidence',
            'Not: Bu hafta Snatch High Pull yok.',
            'Mevcut teknik problem barı gereğinden fazla yükseltmek olduğu için ekstra high-pull hacmi eklenmiyor.',
          ],
        },
        {
          id: 'w7-a-olympic-lift',
          title: 'Olympic Lift — Squat Snatch',
          items: [
            'Squat Snatch — 6×2',
            'Set 1–2: 45 kg',
            'Set 3–4: 47.5 kg',
            'Set 5–6: 50 kg',
            'Yaklaşık: %70–77',
            'QUALITY GATE:',
            '45 kg kaliteli → 47.5 kg',
            '47.5 kg’da Direct Squat Catch + bar belirgin öne kaçmıyor + barın maksimum yüksekliğe çıkmasını beklemeden pull-under başlıyor → 50 kg',
            'Aksi durumda ağırlık artırılmaz.',
            'RPE: ≤7.5',
            'Dinlenme: 2 dk',
            'ANA CUE: EXTENSION BİTTİ → KENDİNİ AŞAĞI ÇEK.',
            'Her lift sonrası değerlendir: Barı fazla yukarı mı çektim?',
            'Yoksa bar yükselirken altına mı girdim?',
          ],
        },
        {
          id: 'w7-a-gymnastics',
          title: 'Gymnastics — Butterfly',
          items: [
            'Primer: 2×5 Hollow-to-Arch Kip Swing',
            'Yavaş ve kontrollü.',
            'Ardından: 4×8 Butterfly Pull-Up',
            'Dinlenme: 90 sn',
            'Toplam hedef: 32 kaliteli tekrar',
            'QUALITY STANDARD:',
            '1. Aktif Push-Away',
            '2. Tepeden dikey / strict descent yok',
            '3. Circular Rhythm',
            '4. Bacaklar uzun',
            '5. Ayaklar mümkün olduğunca birlikte',
            '6. Son tekrarın mekaniği ilk tekrara benzer',
            'Örnek: 8 tekrar hedeflenirken 1–6 kaliteli, 7–8 strict descent olursa SET = 6 kaliteli rep.',
            'Rep sayısı uğruna teknik bozulmayacak.',
            'Hedef: 8 / 8 / 8 / 8 ve tamamının kaliteli olması.',
            'QUALITY × REPS',
          ],
        },
        {
          id: 'w7-a-strength',
          title: 'Strength — Back Squat',
          items: [
            'Back Squat — 4×4 @85 kg',
            '≈ %77.5',
            'Dinlenme: 2–3 dk',
            'RPE: 7.5–8',
            'Grind yok.',
          ],
        },
        {
          id: 'w7-a-metcon',
          title: 'Metcon — Running Capacity',
          items: [
            '5 Rounds',
            '400 m Run',
            'Her round sonrası 90 sn Rest',
            'All-out test değil.',
            'Amaç: Repeatable Running Pace',
            'Skor: R1 ____ / R2 ____ / R3 ____ / R4 ____ / R5 ____',
            'Ana metrik: En hızlı ve en yavaş 400 m arasındaki fark.',
            'Hedef: ≤10–12 sn',
            'Pacing R1: Kontrollü',
            'Pacing R2–4: R1 pace’i koru',
            'Pacing R5: Kapasite varsa hızlan',
            'RPE: 7.5–8',
          ],
        },
        {
          id: 'w7-a-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '3 tur',
            '10 Single-Arm DB Row / kol @22.5 kg',
            '12 GHD Hip Extension',
            '12 Hollow Rock',
          ],
        },
        {
          id: 'w7-a-cool-down',
          title: 'Cool Down',
          items: ['5 dk Easy Walk', 'Calf', 'Hip', 'Lat'],
        },
      ],
    },

    {
      id: 'block-1-week-7-day-b',
      day: 'DAY B',
      title: 'Clean + Double Under + Strict Strength',
      duration: '80–90 dk',
      focus:
        'Double Under Benchmark · Squat Clean · Strict Pull-Up · Front Squat · Repeatability',
      purpose:
        'Double Under’ı Day D bağımlılığından çıkarıp ilk gerçek benchmarkı almak, kontrollü Clean drill kalitesini sürdürmek ve yük altında Squat Clean paternini korumak.',
      sections: [
        {
          id: 'w7-b-warm-up',
          title: 'Warm-up',
          duration: '8–10 dk',
          items: [
            '2 tur',
            '200 m Bike veya Row',
            '8 Cossack Squat',
            '8 Front Rack Lunge',
            '10 Band Pull-Apart',
            'Empty Bar: 5 Clean Deadlift',
            '5 Tall Clean',
            '5 Front Squat',
            '5 High-Hang Squat Clean',
          ],
        },
        {
          id: 'w7-b-double-under',
          title: 'Skill Micro-Dose — Double Under',
          duration: '8 dk',
          items: [
            '2 dk: Single Under',
            '3 dk: Single-Single-Double + Linked Transition',
            '3 dk: Double Under bağlantı denemeleri',
            'Kural: Failure spam yok.',
            'Takıl → Reset → Tekrar kaliteli deneme',
            'Bu bir conditioning parçası değil.',
            'Günün ana skoru — En uzun Unbroken Double Under: _____ rep',
            'Bu değer ilk gerçek DU benchmark olacak.',
          ],
        },
        {
          id: 'w7-b-olympic-drill',
          title: 'Olympic Drill — Clean',
          items: [
            'Tall Clean — 3×3 @40 kg',
            'Her tekrar arasında 3–5 sn reset',
            'Clean High Pull — 2×3 @50–55 kg',
            'ANA CUE: LONG ARMS UNTIL EXTENSION',
            'High-Hang Squat Clean — 2×2 @50 kg',
            'Dinlenme: 75–90 sn',
            'Burası metcon değil.',
            'Her tekrar ayrı teknik lift olarak yapılacak.',
          ],
        },
        {
          id: 'w7-b-olympic-lift',
          title: 'Olympic Lift — Squat Clean',
          items: [
            'Squat Clean — 6×2',
            'Set 1–2: 62.5 kg',
            'Set 3–4: 67.5 kg',
            'Set 5–6: 70 kg',
            'Yaklaşık: %70–77.5',
            'QUALITY GATE:',
            '67.5 kg’da Squat Clean korunuyor + Early Arm Bend belirgin değil + bar öne kaçmıyor → 70 kg',
            'Aksi durumda 67.5 kg’da kal.',
            'ANA CUE: LONG ARMS → FINISH → UNDER.',
            'RPE: ≤8',
            'Dinlenme: 2 dk',
            'Takip — Direct Squat Clean: ____ / 12',
            'Takip — Power Catch + Front Squat: ____ / 12',
            'Takip — Early Arm Bend: ____ / 12',
          ],
        },
        {
          id: 'w7-b-gymnastics',
          title: 'Gymnastics — Strict Pull-Up',
          items: [
            'Strict Pull-Up — 5×4',
            'Toplam hedef: 20 tam ROM rep',
            'Standart: Dead Hang → Strict Pull → Chin Over Bar → Controlled Full Extension',
            'Eksik ROM tekrar sayılmaz.',
            'Dinlenme: 90–120 sn',
          ],
        },
        {
          id: 'w7-b-strength',
          title: 'Strength — Front Squat',
          items: [
            'Front Squat — 5×3 @80 kg',
            '≈ %77.5',
            'Dinlenme: 2–2.5 dk',
            'RPE: ≤8',
            'Pause yok.',
            'Amaç: Week 6’ya göre hacim biraz azalırken intensity artıyor.',
          ],
        },
        {
          id: 'w7-b-metcon',
          title: 'Metcon — EMOM 12',
          items: [
            '12 min EMOM — 4 tur',
            'Min 1: 12/10 Cal Bike',
            'Min 2: 12 Wall Ball @9 kg',
            'Min 3: 8 Toes-to-Bar',
            'Amaç: Threshold altında kaliteli repeatability.',
            'Hedef: Her dakikanın sonunda yaklaşık 10–15 sn boşluk bırakabilmek.',
            'T2B kalitesi bozulursa: 8 → 6',
            'RPE: 7.5–8',
          ],
        },
        {
          id: 'w7-b-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            'Single-Arm DB Strict Press — 3×8 / kol @12.5–17.5 kg',
            'İki taraf aynı tekrar.',
            'Sol taraf için ekstra hacim yok.',
            'Face Pull — 2×12',
          ],
        },
        {
          id: 'w7-b-cool-down',
          title: 'Cool Down',
          items: ['5 dk', 'Front Rack', 'Quad', 'Hip', 'Lat'],
        },
      ],
    },

    {
      id: 'block-1-week-7-day-c',
      day: 'DAY C',
      title: 'Jerk + Butterfly Under Fatigue + Competition Capacity',
      duration: '80–90 dk',
      focus:
        'Split Jerk · Butterfly Under Fatigue · Push Press · Competition Capacity',
      purpose:
        'Jerk teknik kalitesini korumak, Butterfly mekaniğini yükselmiş solunum altında test etmek ve competition capacity stimulusunu almak.',
      sections: [
        {
          id: 'w7-c-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            '2 tur',
            '200 m Ski',
            '10 Walking Lunge',
            '10 Scap Push-Up',
            '10 Band Pull-Apart',
            'Empty Bar: 5 Strict Press',
            '5 Push Press',
            '5 Push Jerk',
            '5 Split Jerk',
          ],
        },
        {
          id: 'w7-c-olympic-drill',
          title: 'Olympic Drill — Jerk',
          items: [
            'Jerk Balance — 3×3 @40 kg',
            'Tall Jerk — 3×2 @40 kg',
            'Pause Split Jerk — 2×2 @50 kg',
            'Catch pozisyonunda 2 sn pause',
          ],
        },
        {
          id: 'w7-c-olympic-lift',
          title: 'Olympic Lift — Split Jerk',
          items: [
            'Split Jerk — 6×2',
            'Set 1–2: 55 kg',
            'Set 3–4: 60 kg',
            'Set 5–6: 62.5 kg',
            'RPE: ≤8',
            'Dinlenme: 2 dk',
            'QUALITY GATE: Stable Split + Fast Lockout + Bar Midline',
            'Teknik iyiyse kilo artır.',
          ],
        },
        {
          id: 'w7-c-gymnastics',
          title: 'Gymnastics — Butterfly Under Fatigue',
          items: [
            'Eğer Day A’daki 4×8 Butterfly kaliteli çıktıysa:',
            '4 set',
            '8 Cal Ski',
            'Hemen ardından 6 Butterfly Pull-Up',
            'Dinlenme: 75 sn',
            'Amaç: Day A’daki kaliteli Butterfly mekaniğini solunum yükselmişken korumak.',
            'Quality Standard: Push-Away · Circular Descent · Long Legs · No Strict Descent',
            'Eğer Day A Butterfly kalitesi kötüyse:',
            'Ski kaldırılır.',
            '4×6 Teknik Butterfly',
            'Dinlenme: 75–90 sn',
          ],
        },
        {
          id: 'w7-c-strength',
          title: 'Strength — Push Press',
          items: [
            'Push Press — 4×4',
            'İlk set: 50 kg',
            'Bar speed iyi + teknik temiz + RPE uygun → 52.5 kg',
            'RPE: ≤8',
            'Dinlenme: 2 dk',
          ],
        },
        {
          id: 'w7-c-metcon',
          title: 'Metcon — Buy-In / AMRAP / Buy-Out',
          items: [
            'For Time',
            'Buy-In: 30/24 Cal Row',
            'Ardından 10 min AMRAP:',
            '6 Box Jump Over @24"',
            '8 Single-DB Front Rack Walking Lunge @22.5 kg',
            '10 Burpee',
            'Buy-Out: 30/24 Cal Row',
            'Time Cap: 16 dk',
            'Amaç: İlk Row’da kendini öldürme. AMRAP boyunca sürekli hareket et. Buy-Out Row’da kalan kapasiteyi kullan.',
            'Pacing Buy-In: Kontrollü güçlü',
            'Pacing AMRAP: Sürdürülebilir',
            'Pacing Buy-Out: Progressive push',
            'RPE: 8–8.5',
            'Skor — Toplam süre: _____',
            'Skor — AMRAP sonucu: _____ tur + _____',
          ],
        },
        {
          id: 'w7-c-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '2–3 tur',
            '10 GHD Sit-Up',
            '10 DB Bench Press / kol @17.5 kg',
            '12 Band External Rotation',
          ],
        },
        {
          id: 'w7-c-cool-down',
          title: 'Cool Down',
          duration: '5–8 dk',
          items: ['Shoulder', 'Lat', 'Hip', 'T-Spine'],
        },
      ],
    },

    {
      id: 'block-1-week-7-day-d',
      day: 'DAY D',
      title: 'Optional Athletic Development',
      duration: '45–55 dk',
      focus:
        'Double Under · Strict Pull-Up · RDL · Structural/Hypertrophy · Zone 2',
      purpose:
        'Opsiyonel gün. Day B’deki DU benchmarkını kaliteli şekilde tekrar etmek veya geçmek ve structural/aerobic gelişimi desteklemek. Haftalık adherence hesabına dahil edilmez.',
      sections: [
        {
          id: 'w7-d-warm-up',
          title: 'Warm-up',
          items: ['5–8 dk Easy Movement'],
        },
        {
          id: 'w7-d-double-under',
          title: 'Double Under',
          duration: '15 dk',
          items: [
            'Amaç: Day B’deki DU benchmarkını kaliteli şekilde tekrar etmek veya geçmek.',
            'Failure spam yok.',
            'En uzun UB: _____ rep',
          ],
        },
        {
          id: 'w7-d-strict-pull-up',
          title: 'Strict Pull-Up',
          items: ['Strict Pull-Up — 3×3', 'Tam ROM', 'RPE: 6–7'],
        },
        {
          id: 'w7-d-rdl',
          title: 'RDL',
          items: ['RDL — 4×6 @82.5–85 kg', 'RPE: 7'],
        },
        {
          id: 'w7-d-structural',
          title: 'Structural / Hypertrophy',
          items: [
            '3 tur',
            '10 DB Bench Press / kol',
            '10 Bulgarian Split Squat / bacak',
            '12 GHD Hip Extension',
          ],
        },
        {
          id: 'w7-d-zone2',
          title: 'Zone 2',
          duration: '15–20 dk',
          items: ['RPE: 4–5'],
        },
        {
          id: 'w7-d-cool-down',
          title: 'Cool Down',
          duration: '5 dk',
          items: ['5 dk Cool Down'],
        },
      ],
    },
  ],
};

export default block1Week7;
