import type { TrainingWeek } from '../../types/training';

const block1Week8: TrainingWeek = {
  id: 'block-1-week-8',
  block: 1,
  week: 8,
  title: 'Technical Consolidation + Butterfly Reset I',
  description:
    'Butterfly mechanics reset, Snatch bar path + catch synchronization, Clean consistency, strict pulling strength, strength progression and conditioning. Weekly target RPE 7–8. Technique > load. No failure. Olympic lifts use quality singles. DU progression paused. Accessory and Day D optional. No sandbag.',

  days: [
    {
      id: 'block-1-week-8-day-a',
      day: 'DAY A',
      title: 'Snatch + Butterfly Reset + Back Squat',
      duration: '85–90 min',
      focus:
        'Snatch Bar Path · Catch Synchronization · Butterfly Mechanics · Back Squat · Conditioning',
      purpose:
        'Snatch bar path ve catch senkronizasyonunu geliştirmek, Butterfly mekaniğini düşük tekrar kaliteli exposure ile resetlemek ve squat strength progresyonunu sürdürmek.',
      sections: [
        {
          id: 'w8-a-warm-up',
          title: 'Warm-up',
          items: [
            '2 Rounds',
            '200 m Row',
            '8 Walking Lunge',
            '10 Air Squat',
            '10 Scap Pull-Up',
            '8 PVC Overhead Squat',
            '8 PVC Snatch',
            'Empty Bar:',
            '5 Snatch Grip RDL',
            '5 Muscle Snatch',
            '5 High-Hang Squat Snatch',
            '5 Overhead Squat',
          ],
        },
        {
          id: 'w8-a-snatch-primer',
          title: 'Snatch Technical Primer',
          items: [
            'A) Muscle Snatch — 3×3 @25–30 kg',
            'Focus: Keep bar close',
            'Elbows high/out',
            'No forward looping',
            'B) Tall Snatch — 3×2 @30 kg',
            '3–5 sec reset between reps',
            'Active turnover',
            'Fast under',
            'Keep bar close',
            'C) Drop Snatch — 2×2 @30–35 kg',
            'Lockout + squat descent connected',
            'No Catch → OHS pattern',
          ],
        },
        {
          id: 'w8-a-snatch',
          title: 'Squat Snatch — Technical Singles',
          items: [
            '8×1',
            '2×1 @45 kg',
            '2×1 @47.5 kg',
            '2×1 @50 kg',
            '2×1 @52.5 kg',
            'Rest: 90–120 sec',
            'RPE Cap: 8',
            '52.5 KG QUALITY GATE:',
            'Only increase to 52.5 kg if 50 kg has:',
            'Close bar path',
            'Complete extension',
            'Active pull-under',
            'Squat catch',
            'No significant forward displacement',
            'MAIN CUE: KEEP IT CLOSE → FINISH → UNDER',
            'Do NOT intentionally limit bar height.',
            'Bar reaching chest height is not automatically a fault.',
            'Waiting for the bar to reach chest height before going under is the fault.',
            'LOG — Squat Catch: __ / 8',
            'LOG — Significant Looping: __ / 8',
            'LOG — Catch → Additional Squat: __ / 8',
            'LOG — Early Hip Rise: __ / 8',
          ],
        },
        {
          id: 'w8-a-butterfly',
          title: 'Butterfly Reset — Exposure 1',
          items: [
            'A) Floor Hollow → Arch — 2×8',
            'Focus: Feet together · Long legs · Point toes',
            'B) Straight-Arm Butterfly Kip Swing — 3×6–8',
            'Arms stay straight',
            'Cue: CHEST THROUGH → HEAD FOLLOWS',
            'C) Sponge/Foam Constraint Butterfly — 3×4',
            'Foam between legs',
            'No knee bend',
            'Feet together',
            'Hip-driven rhythm',
            'D) Full Butterfly — 3×3–5',
            'Maximum: 15 quality reps',
            'STOP SET IF:',
            'Early arm bend',
            'Strict descent',
            'Knee bend',
            'Feet separation',
            'Circular rhythm loss',
          ],
        },
        {
          id: 'w8-a-strength',
          title: 'Strength — Back Squat',
          items: [
            '5×3 @87.5 kg',
            'Approx. 80% 1RM',
            'Rest: 2:00–2:30',
            'Target RPE: 7.5–8',
            'No grind.',
          ],
        },
        {
          id: 'w8-a-metcon',
          title: 'Metcon',
          items: [
            '5 Rounds For Time',
            '6 Power Clean @50 kg',
            '10 Box Jump Over @24"',
            '12/10 cal BikeErg',
            'Target: 10–13 min',
            'CAP: 15 min',
            'RPE: 8',
            'Power Clean: Touch-and-Go allowed.',
            'Switch to singles if cycling mechanics deteriorate.',
          ],
        },
        {
          id: 'w8-a-accessory',
          title: 'Accessory — Optional',
          items: [
            '2–3 Rounds',
            '10 Single-Arm DB Row / arm @22.5 kg',
            '10 GHD Hip Extension',
            '12 Hollow Rock',
          ],
        },
        {
          id: 'w8-a-cooldown',
          title: 'Cool Down',
          items: ['Easy cool down'],
        },
      ],
    },

    {
      id: 'block-1-week-8-day-b',
      day: 'DAY B',
      title: 'Clean + Butterfly Reset + Strict Pull',
      duration: '85–90 min',
      focus:
        'Clean Consistency · Butterfly Mechanics · Dead-Stop Strict Pull-Up · Front Squat · Threshold',
      purpose:
        'Clean paternini teknik singles ile tekrar test etmek, Butterfly reset exposure eklemek ve Dead-Stop Strict Pull-Up ile full-ROM pulling kapasitesini ölçmek.',
      sections: [
        {
          id: 'w8-b-warm-up',
          title: 'Warm-up',
          items: [
            '2 Rounds',
            '200 m Bike or Row',
            '8 Cossack Squat',
            '8 Front Rack Lunge',
            '10 Band Pull-Apart',
            'Empty Bar:',
            '5 Clean Deadlift',
            '5 Tall Clean',
            '5 Front Squat',
            '5 High-Hang Squat Clean',
          ],
        },
        {
          id: 'w8-b-butterfly',
          title: 'Butterfly Reset — Exposure 2',
          items: [
            'A) Floor Hollow → Arch — 2×8',
            'B) Straight-Arm Butterfly Kip Swing — 3×6',
            'Cue: CHEST THROUGH → HEAD FOLLOWS',
            'C) Sponge/Foam Constraint Butterfly — 3×4',
            'D) Full Butterfly — 3×3–5',
            'Maximum: 15 quality reps',
            'STOP SET IF:',
            'Early arm bend',
            'Strict descent',
            'Knee bend',
            'Feet separation',
            'Circular rhythm loss',
          ],
        },
        {
          id: 'w8-b-clean-primer',
          title: 'Clean Technical Primer',
          items: [
            'A) Tall Clean — 3×2 @40 kg',
            '3–5 sec reset between reps',
            'B) Clean High Pull — 2×3 @50 kg',
            'Cue: LONG ARMS → FINISH',
            'C) High-Hang Squat Clean — 2×2 @50 kg',
            'Focus: Direct Squat Catch',
          ],
        },
        {
          id: 'w8-b-clean',
          title: 'Squat Clean — Consistency Retest',
          items: [
            '8×1',
            '2×1 @60 kg',
            '2×1 @62.5 kg',
            '2×1 @65 kg',
            '2×1 @67.5 kg',
            'Rest: 90–120 sec',
            'RPE Cap: 8',
            'MAIN CUE: LONG ARMS → FINISH → UNDER',
            '67.5 KG QUALITY GATE:',
            'Minimal/no early arm bend',
            'Complete extension',
            'Close bar path',
            'Direct Squat Clean',
            'No Power Catch + Front Squat',
            'LOG — Direct Squat Clean: __ / 8',
            'LOG — Early Arm Bend: __ / 8',
            'LOG — Forward Bar Path: __ / 8',
            'LOG — Fail: __ / 8',
          ],
        },
        {
          id: 'w8-b-pullup',
          title: 'Dead-Stop Strict Pull-Up — Test',
          items: [
            '5×5 @Bodyweight',
            'Rest: 2 min',
            'EVERY REP:',
            'Full dead hang',
            'Full elbow extension',
            'Approx. 2 sec bottom reset',
            'Strict pull',
            'Chin clearly over bar',
            'Controlled descent',
            'Target: 25 / 25 Full-ROM Reps',
            'No failure.',
            'No partial ROM.',
            'No kip.',
            'If 25/25 is completed cleanly:',
            'Week 9 candidate → Weighted Dead-Stop Strict Pull-Up 5×3 @BW +2.5 kg',
          ],
        },
        {
          id: 'w8-b-strength',
          title: 'Strength — Front Squat',
          items: [
            '4×4 @82.5 kg',
            'Approx. 78.5% 1RM',
            'RPE Cap: 8',
            'If RPE >8 by Set 3 → Final set @80 kg',
          ],
        },
        {
          id: 'w8-b-metcon',
          title: 'Metcon — Threshold',
          items: [
            '4 Rounds',
            '2:30 WORK',
            '1:00 REST',
            'During each 2:30 work interval:',
            '10 Wall Ball @9 kg',
            '8 Toes-to-Bar',
            'Remaining Time → Row Calories',
            'Score — R1 Row Cal: __',
            'Score — R2 Row Cal: __',
            'Score — R3 Row Cal: __',
            'Score — R4 Row Cal: __',
            'Target: R1 → R4 degradation ≤15%',
            'Goal: Wall Ball preferably UB',
            'Goal: T2B preferably UB',
            'Goal: Sustainable Row output',
          ],
        },
        {
          id: 'w8-b-accessory',
          title: 'Accessory — Optional',
          items: [
            'Single-Arm DB Strict Press — 3×8 / arm @12.5–17.5 kg',
            'Face Pull — 2×12',
          ],
        },
        {
          id: 'w8-b-cooldown',
          title: 'Cool Down',
          items: ['Easy cool down'],
        },
      ],
    },

    {
      id: 'block-1-week-8-day-c',
      day: 'DAY C',
      title: 'Jerk + Butterfly Transfer + Competition',
      duration: '80–90 min',
      focus:
        'Split Jerk · Butterfly Transfer · Push Press · Competition Conditioning',
      purpose:
        'Jerk teknik kalitesini korumak, Butterfly reset mekaniğini fatigue preload olmadan üçüncü exposure ile pekiştirmek ve competition conditioning kapasitesini sürdürmek.',
      sections: [
        {
          id: 'w8-c-warm-up',
          title: 'Warm-up',
          items: [
            '2 Rounds',
            '200 m SkiErg',
            '8 Walking Lunge',
            '10 Scap Push-Up',
            '10 Band Pull-Apart',
            'Empty Bar:',
            '5 Strict Press',
            '5 Push Press',
            '5 Push Jerk',
            '5 Split Jerk',
          ],
        },
        {
          id: 'w8-c-jerk-primer',
          title: 'Jerk Technical Primer',
          items: [
            'A) Jerk Balance — 3×2 @40 kg',
            'B) Tall Jerk — 2×2 @40 kg',
            'C) Pause Split Jerk — 2×2 @50 kg',
            '2 sec hold in catch',
          ],
        },
        {
          id: 'w8-c-jerk',
          title: 'Split Jerk',
          items: [
            '6×2',
            '2×2 @57.5 kg',
            '2×2 @62.5 kg',
            '2×2 @65 kg',
            'RPE Cap: 8',
            '65 KG QUALITY GATE:',
            'Stable split',
            'Fast lockout',
            'Bar on midline',
            'No press-out',
            'Controlled recovery',
            'If 62.5 kg deteriorates: Do NOT increase to 65 kg.',
          ],
        },
        {
          id: 'w8-c-butterfly',
          title: 'Butterfly Reset — Exposure 3',
          items: [
            'NO FATIGUE PRELOAD THIS WEEK.',
            'A) Straight-Arm Butterfly Kip — 2×6',
            'B) Sponge/Foam Constraint Butterfly — 2×4',
            'C) Full Butterfly — 3×3–5',
            'Maximum: 15 quality reps',
            'Focus: Reduce early arm bend',
            'Focus: Chest through',
            'Focus: Circular descent',
            'Focus: Long legs',
            'Focus: Feet together',
            'Focus: No strict descent',
          ],
        },
        {
          id: 'w8-c-strength',
          title: 'Strength — Push Press',
          items: [
            '4×4 @50–52.5 kg',
            'Set 1 @50 kg',
            'If bar speed and technique are good → 52.5 kg',
            'RPE Cap: 8',
          ],
        },
        {
          id: 'w8-c-metcon',
          title: 'Competition Metcon — Chipper',
          items: [
            'FOR TIME',
            '20/16 cal SkiErg',
            'THEN 3 Rounds:',
            '10 Alternating DB Snatch @22.5 kg',
            '8 Burpee Box Jump Over @24"',
            '10 Single-DB Front Rack Walking Lunge @22.5 kg',
            'THEN',
            '20/16 cal SkiErg',
            'Target: 11–14 min',
            'CAP: 15 min',
            'RPE: 8–8.5',
            'Focus: Fast transitions',
            'Focus: Sustainable DB cycling',
            'Focus: Controlled burpee pace',
            'Focus: Increase output on final SkiErg',
          ],
        },
        {
          id: 'w8-c-accessory',
          title: 'Accessory — Optional',
          items: [
            '2 Rounds',
            '10 GHD Sit-Up',
            '10 DB Bench / arm @17.5 kg',
            '12 Band External Rotation',
          ],
        },
        {
          id: 'w8-c-cooldown',
          title: 'Cool Down',
          items: ['Easy cool down'],
        },
      ],
    },

    {
      id: 'block-1-week-8-day-d',
      day: 'DAY D',
      title: 'Optional — Structural + Zone 2',
      duration: '45–55 min',
      focus:
        'Dead-Stop Strict Pull-Up · RDL · Structural Strength · Zone 2',
      purpose:
        'Tamamen opsiyonel destek günü. DU progresyonu yapılmaz ve haftalık completion hesabına dahil edilmez.',
      optional: true,
      sections: [
        {
          id: 'w8-d-rules',
          title: 'Day D Rules',
          items: [
            'Day D is completely optional.',
            'Does NOT count toward weekly completion.',
            'No DU progression this week.',
          ],
        },
        {
          id: 'w8-d-warm-up',
          title: 'Warm-up',
          duration: '5 min',
          items: ['5 min easy movement'],
        },
        {
          id: 'w8-d-pullup',
          title: 'Easy Dead-Stop Strict Pull-Up',
          items: [
            '3×3 @Bodyweight',
            'Full ROM',
            'Approx. 2 sec bottom reset',
            'Stay far from failure',
          ],
        },
        {
          id: 'w8-d-rdl',
          title: 'RDL',
          items: [
            '4×6 @85 kg',
            'RPE: 7–7.5',
          ],
        },
        {
          id: 'w8-d-structural',
          title: 'Structural',
          items: [
            '3 Rounds',
            '10 DB Bench / arm',
            '10 Bulgarian Split Squat / leg',
            '12 GHD Hip Extension',
          ],
        },
        {
          id: 'w8-d-zone2',
          title: 'Zone 2',
          duration: '15–20 min',
          items: [
            'Bike / Row / Treadmill',
            'RPE: 4–5',
          ],
        },
        {
          id: 'w8-d-cooldown',
          title: 'Cool Down',
          items: ['Easy cool down'],
        },
      ],
    },
  ],
};

export default block1Week8;