import type { TrainingWeek } from '../../types/training';

const block1Week2: TrainingWeek = {
  id: 'block-1-week-2',
  block: 1,
  week: 2,
  title: 'Butterfly Rhythm & Strength Under Fatigue',
  description:
    "Butterfly ritmini standartlaştırma, Snatch bar yolunu geliştirme, Clean'i yorgunluk altında koruma ve Strict Pull-up'ta tam ROM.",
  days: [
    {
      id: 'block-1-week-2-day-a',
      day: 'DAY A',
      title: 'Olympic Speed & Gymnastics',
      duration: '80–90 dk',
      focus: 'Snatch bar yolu, güçlü extension ve kaliteli butterfly ritmi.',
      purpose:
        'Snatch tekniğini hız odaklı geliştirirken butterfly pull-up ritmini failure oluşturmadan standartlaştırmak.',
      sections: [
        {
          id: 'w2-a-warm-up',
          title: 'Warm-up',
          duration: '12 dk',
          items: [
            'Ayakkabı: TYR Lifter → Metcon',
            '3 tur:',
            '250 m Row',
            '10 Air Squat',
            '10 Walking Lunge',
            '10 Scap Push-up',
            '10 PVC Pass Through',
            '10 PVC Overhead Squat',
            'Bar Prep:',
            '10 Snatch Grip RDL',
            '10 Muscle Snatch',
            '10 Snatch Balance',
            'Amaç: Kalça aktivasyonu, omuz hazırlığı ve overhead stabilite.',
          ],
        },
        {
          id: 'w2-a-olympic-drill',
          title: 'Olympic Drill',
          items: [
            'Halting Snatch Deadlift — 4×3 @ %70 / 42.5 kg',
            'Dinlenme: 60 sn',
            'Snatch High Pull — 4×3 @ 45 kg',
            'Hang Power Snatch — 4×2 @ 47.5 kg',
            'Teknik: Kalça erken kalkmayacak.',
            'Teknik: Bar vücuda yakın kalacak.',
            'Teknik: Aktif pull-under.',
          ],
        },
        {
          id: 'w2-a-olympic-lift',
          title: 'Olympic Lift',
          items: [
            'Snatch — 6×2 @ %80 / 52.5 kg',
            'RPE: 7',
            'Dinlenme: 2 dk',
            'Video: Son 2 set',
            'Odak: Güçlü extension.',
            'Odak: Bar ileri gitmeyecek.',
            'Odak: Stabil yakalama.',
          ],
        },
        {
          id: 'w2-a-gymnastics',
          title: 'Gymnastics',
          duration: '10 dk',
          items: [
            'Butterfly Practice',
            'Her sette 4–6 kaliteli Butterfly Pull-up',
            'Dinlenme: 45–60 sn',
            'Amaç: Push Away.',
            'Amaç: Dairesel ritim.',
            'Failure yok.',
          ],
        },
        {
          id: 'w2-a-strength',
          title: 'Strength',
          items: [
            'Back Squat — 5×4 @ %75 / 82.5 kg',
            'Tempo: 31X1',
            'Dinlenme: 2–3 dk',
            'RPE: 7',
          ],
        },
        {
          id: 'w2-a-metcon',
          title: 'Metcon — Sprint Couplet',
          items: [
            '7 RFT',
            '5 Power Snatch @ 42.5 kg',
            '7 Box Jump Over @ 24"',
            'Time Cap: 10 dk',
            'Hedef: İlk tur temposu son turda korunacak.',
          ],
        },
        {
          id: 'w2-a-accessory',
          title: 'Accessory',
          items: [
            '3 tur:',
            '10 Hollow Body Rock',
            '20 sn Active Hang',
            '15 Face Pull',
            '10 Arch Rock',
            'Dinlenme: 45 sn',
          ],
        },
        {
          id: 'w2-a-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Bike',
            'Lat Stretch',
            'Hip Stretch',
            'Thoracic Rotation',
            'Box Breathing',
          ],
        },
      ],
    },
    {
      id: 'block-1-week-2-day-b',
      day: 'DAY B',
      title: 'Strength Under Fatigue',
      duration: '80–90 dk',
      focus: 'Clean tekniği, tam ROM strict pull-up ve front squat kuvveti.',
      purpose:
        "Yüksek nabız altında Clean kalitesini korumak ve Strict Pull-up'ta tam hareket açıklığını standartlaştırmak.",
      sections: [
        {
          id: 'w2-b-warm-up',
          title: 'Warm-up',
          items: [
            'Ayakkabı: TYR Lifter → Metcon',
            '3 tur:',
            '200 m Row',
            '10 Cossack Squat',
            '10 Band Pull Apart',
            '10 Front Rack Lunge',
            '10 Muscle Clean',
            '5 Tall Clean',
          ],
        },
        {
          id: 'w2-b-olympic-drill',
          title: 'Olympic Drill',
          items: [
            'Tall Clean — 4×3 @ 40 kg',
            'Clean High Pull — 4×3 @ 50 kg',
            'Hang Clean — 3×2 @ 55 kg',
            'Teknik: Kalçadan güç üret.',
            'Teknik: Kollar erken çekmeyecek.',
            'Teknik: Hızlı rack.',
          ],
        },
        {
          id: 'w2-b-olympic-lift',
          title: 'Olympic Lift',
          items: [
            'Clean — 6×2 @ %77.5 / 70 kg',
            'RPE: 7',
            'Dinlenme: 2 dk',
            'Video: Son set',
          ],
        },
        {
          id: 'w2-b-gymnastics',
          title: 'Gymnastics',
          items: [
            'Strict Pull-up — 5×5',
            'Tempo: 21X1',
            'Dinlenme: 90 sn',
            'Amaç: Her tekrar tam ROM.',
          ],
        },
        {
          id: 'w2-b-strength',
          title: 'Strength',
          items: [
            'Front Squat — 5×4 @ %75 / 77.5 kg',
            'Tempo: 31X1',
            'Dinlenme: 2–3 dk',
            'RPE: 7',
          ],
        },
        {
          id: 'w2-b-metcon',
          title: 'Metcon — Interval Builder',
          items: [
            '5 set',
            "Her 3:00'te bir:",
            '250 m Row',
            '6 Hang Clean @ 55 kg',
            'Kalan süre dinlen.',
            'Amaç: Yüksek nabız altında kaliteli Clean.',
          ],
        },
        {
          id: 'w2-b-accessory',
          title: 'Accessory',
          items: [
            '3 tur:',
            '10 Bulgarian Split Squat / bacak',
            '12 Ring Row',
            '15 Band External Rotation',
            '30 sn Farmer Hold',
            'Dinlenme: 60 sn',
          ],
        },
        {
          id: 'w2-b-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Bike',
            'Front Rack Stretch',
            'Hip Stretch',
            'Thoracic Rotation',
            'Controlled Breathing',
          ],
        },
      ],
    },
    {
      id: 'block-1-week-2-day-c',
      day: 'DAY C',
      title: 'Competition Capacity',
      duration: '85–95 dk',
      focus: 'Split Jerk tekniği, butterfly kalitesi ve yarışma tipi chipper.',
      purpose:
        'Jerk stabilitesini geliştirirken uzun chipper içinde tempo, geçiş ve barbell tekniğini korumak.',
      sections: [
        {
          id: 'w2-c-warm-up',
          title: 'Warm-up',
          duration: '12 dk',
          items: [
            'Ayakkabı: TYR Lifter → Metcon',
            '3 tur:',
            '300 m Row',
            '10 Walking Lunge',
            '10 Scap Push-up',
            '10 PVC Pass Through',
            '10 Empty Bar Push Press',
            '5 Split Jerk Footwork',
            '5 Tall Jerk',
            'Amaç: Omuz aktivasyonu.',
            'Amaç: Jerk pozisyonu.',
            'Amaç: Kalça aktivasyonu.',
          ],
        },
        {
          id: 'w2-c-olympic-drill',
          title: 'Olympic Drill',
          items: [
            'Jerk Balance — 4×3 @ 40 kg',
            'Tall Jerk — 4×2 @ 40 kg',
            'Split Jerk Footwork — 3×5 PVC',
            'Teknik: Dikey dip.',
            'Teknik: Agresif drive.',
            'Teknik: Hızlı split.',
            'Teknik: Stabil iniş.',
          ],
        },
        {
          id: 'w2-c-olympic-lift',
          title: 'Olympic Lift',
          items: [
            'Split Jerk — 6×2 @ %77.5 / 62.5 kg',
            'RPE: 7',
            'Dinlenme: 2 dk',
            'Video: Son 2 set',
            'Odak: Dip dik.',
            'Odak: Güçlü drive.',
            'Odak: Hızlı lockout.',
            'Odak: Dengeli recovery.',
          ],
        },
        {
          id: 'w2-c-gymnastics',
          title: 'Gymnastics',
          duration: '12 dk',
          items: [
            'Butterfly Practice — 5 set',
            'Her sette 5–8 kaliteli Butterfly Pull-up',
            'Setler arasında 60–90 sn dinlen',
            'Odak: Push Away.',
            'Odak: Ayaklar bitişik.',
            'Odak: Hollow pozisyonunu koru.',
            'Odak: Başını geriye atma.',
            'Odak: Her tekrar aynı kalite.',
          ],
        },
        {
          id: 'w2-c-strength',
          title: 'Strength',
          items: [
            'Push Press — 5×5 @ %72.5 / 55 kg',
            'Tempo: 20X1',
            'Dinlenme: 2 dk',
            'RPE: 7',
          ],
        },
        {
          id: 'w2-c-metcon',
          title: 'Metcon — Competition Chipper',
          items: [
            'For Time',
            'Time Cap: 18 dk',
            '800 m Run',
            '40 Wall Ball @ 9 kg',
            '30 Toes to Bar',
            '20 Power Clean @ 50 kg',
            '10 Shoulder to Overhead @ 50 kg',
            "Hedef: Koşudan sonra ilk Wall Ball'a acele etme.",
            "Hedef: Power Clean'lerde ilk tekrar teknik olacak.",
            "Hedef: Shoulder to Overhead tek nefeste bitirilmeye çalışılacak.",
          ],
        },
        {
          id: 'w2-c-accessory',
          title: 'Accessory',
          items: [
            '3 tur:',
            '12 Hollow Body Rock',
            '20 sn Active Hang',
            '12 Scap Pull-up',
            '20 m Heavy Farmer Carry',
            'Dinlenme: 60 sn',
          ],
        },
        {
          id: 'w2-c-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Walk',
            'Lat Stretch',
            'Hip Flexor Stretch',
            'Thoracic Rotation',
            '90/90 Breathing',
          ],
        },
      ],
    },
    {
      id: 'block-1-week-2-day-d',
      day: 'DAY D',
      title: 'Athletic Development',
      duration: '60–70 dk',
      focus: 'Butterfly tekniği, strict pull-up kuvveti ve Zone 2 kapasitesi.',
      purpose:
        'Opsiyonel teknik ve aerobik gelişim günüyle hareket kalitesini desteklemek ve toparlanabilir hacim oluşturmak.',
      sections: [
        {
          id: 'w2-d-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            'Ayakkabı: Metcon',
            '2 tur:',
            '500 m Bike',
            '10 Air Squat',
            '10 Push-up',
            '10 Ring Row',
            '20 sn Dead Hang',
            '10 PVC Pass Through',
          ],
        },
        {
          id: 'w2-d-skill',
          title: 'Skill',
          duration: '12 dk',
          items: [
            'Butterfly Technique',
            'Her sette 5 kaliteli Butterfly Pull-up',
            '10 sn Active Hang',
            '6 Beat Swing',
            '30–45 sn dinlen',
            'Odak: Push Away.',
            'Odak: Hollow.',
            'Odak: Arch.',
            'Odak: Ritim.',
            'Odak: Kalite.',
            'Failure yok.',
          ],
        },
        {
          id: 'w2-d-gymnastics',
          title: 'Gymnastics',
          items: [
            'Strict Pull-up — 5×4',
            'Tempo: 21X1',
            'Dinlenme: 90 sn',
            'Amaç: Her sette tam ROM.',
          ],
        },
        {
          id: 'w2-d-strength',
          title: 'Strength',
          items: [
            'Romanian Deadlift — 4×8 @ %70 / 80 kg',
            'Tempo: 31X1',
            'Dinlenme: 90 sn',
            'RPE: 7',
          ],
        },
        {
          id: 'w2-d-conditioning',
          title: 'Conditioning — Aerobic Builder',
          duration: '30 dk',
          items: [
            'Zone 2',
            'Tercih: Bike, Row veya Run',
            'Hedef nabız: 130–145 bpm',
            'Amaç: Burundan nefes alabilecek tempo.',
          ],
        },
        {
          id: 'w2-d-accessory',
          title: 'Accessory',
          items: [
            '3 tur:',
            '10 Single Leg Romanian Deadlift / bacak',
            '12 Single Arm DB Row / kol',
            '15 Face Pull',
            '15 Hollow Body Rock',
            '20 Band Pull Apart',
            'Dinlenme: 45–60 sn',
          ],
        },
        {
          id: 'w2-d-cool-down',
          title: 'Cool Down',
          duration: '10 dk',
          items: [
            'Hip Mobility',
            'Hamstring Stretch',
            'Lat Stretch',
            "Child's Pose",
            'Box Breathing',
          ],
        },
      ],
    },
  ],
};

export default block1Week2;