import type { TrainingWeek } from '../../types/training';

const block1Week4: TrainingWeek = {
  id: 'block-1-week-4',
  block: 1,
  week: 4,
  title: 'Deload + Technical Consolidation',
  description:
    'Week 1–3 birikmiş yorgunluğunu azaltma; Snatch ve Clean’de direkt squat catch tekniğini, Butterfly kapasitesini ve bar hızını yeniden konsolide etme haftası. Hedef RPE 6–7. Grind ve failure yok. Accessory tüm günlerde opsiyonel. Sandbag programdan tamamen çıkarıldı.',
  days: [
    {
      id: 'block-1-week-4-day-a',
      day: 'DAY A',
      title: 'Snatch Technique Consolidation',
      duration: '70–80 dk',
      focus: 'Squat Snatch · Overhead Güven · Butterfly Capacity · Back Squat · DB/Ski',
      purpose:
        'Overhead güvenini artırmak, bar altına hızlı giriş ve direkt Squat Snatch catch geliştirmek, Butterfly kapasitesine kontrollü geçiş yapmak ve Back Squat yorgunluğunu azaltmak.',
      sections: [
        {
          id: 'w4-a-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            '2 tur',
            '250 m Row',
            '10 Air Squat',
            '8 Walking Lunge / toplam',
            '10 Scap Push-up',
            '10 PVC Pass Through',
            '8 PVC Overhead Squat',
            'Wrist / Overhead Prep: 10 Wrist Rock',
            '20 sn Prayer Stretch',
            '20 sn PVC Overhead Hold',
            'Barbell Prep: 8 Snatch Grip RDL',
            '6 Muscle Snatch',
            '6 Overhead Squat',
            'Amaç: Bilek ve omuzu overhead pozisyona hazırlamak.',
          ],
        },
        {
          id: 'w4-a-olympic-drill',
          title: 'Olympic Drill',
          duration: '12–15 dk',
          items: [
            'Tall Snatch — 3×3 @ 25–30 kg',
            'Snatch Balance — 3×2 @ 35–40 kg',
            'Paused Overhead Squat — 2×3 @ 35–40 kg',
            'Paused OHS: Dipte 3 sn pause',
            'Dinlenme: 60–75 sn',
            'Odak: Bar altına agresif gir.',
            'Odak: Catch mümkün olduğunca derin olsun.',
            'Odak: Overhead’de aktif omuz.',
            'Odak: Bar başın üzerinde merkezde.',
            'Kural: Bilekte ağrı oluşturacak yük kullanılmayacak.',
          ],
        },
        {
          id: 'w4-a-olympic-lift',
          title: 'Olympic Lift — Squat Snatch',
          items: [
            'Squat Snatch — 5×2 @ %70–72.5 / 45–47.5 kg',
            'RPE: 6–6.5',
            'Dinlenme: 2 dk',
            'Ana kural: Her tekrar Squat Snatch niyetiyle yapılacak.',
            'Power Catch + OHS istemiyoruz.',
            'Takip: 10 tekrarın kaçı gerçek Squat Snatch?',
            'Hedef: En az 8/10 gerçek Squat Catch.',
            'Video: Mümkünse son 2 set.',
          ],
        },
        {
          id: 'w4-a-gymnastics',
          title: 'Gymnastics — Butterfly Capacity',
          items: [
            '4×8–10 Butterfly Pull-up',
            'Dinlenme: 75–90 sn',
            'RPE: ≤7',
            'Odak: Push-away.',
            'Odak: Dairesel aks.',
            'Odak: Baş nötr.',
            'Odak: Ayaklar bitişik.',
            'Odak: Dizleri arkada aşırı bükme.',
            'Odak: Hollow → Arch geçişini koru.',
            'Kural: Teknik bozulduğu anda set biter.',
            '10 tekrar zorunlu değil.',
            'Örnek: 10 / 10 / 9 / 8 teknik temizse kabul.',
            'Failure yok.',
          ],
        },
        {
          id: 'w4-a-strength',
          title: 'Strength — Back Squat',
          items: [
            'Back Squat — 3×4 @ %65–67.5 / 72.5–75 kg',
            'Tempo: 31X1',
            'Dinlenme: 2 dk',
            'RPE: 6–6.5',
            'Amaç: Yorgunluk yaratmak değil, bar hızını korumak.',
          ],
        },
        {
          id: 'w4-a-metcon',
          title: 'Metcon — DB / Ski Technical Interval',
          duration: '10 dk',
          items: [
            '4 set',
            'Her 2:30’da:',
            '8 Alternating DB Snatch @ 22.5 kg',
            '8 Box Jump Over @ 24"',
            '150 m SkiErg',
            'Kalan süre dinlen.',
            'Hedef RPE: 7',
            'Amaç: DB cycling, hızlı geçiş, patlayıcılık ve aerobik toparlanma.',
            'Kural: Sprint değil.',
            '4 set mümkün olduğunca benzer sürede tamamlanacak.',
          ],
        },
        {
          id: 'w4-a-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '2 tur',
            '10 Single Arm DB Row / kol',
            '10 Hollow Body Rock',
            '20 sn Active Hang',
            '12 Band External Rotation / kol',
            'Dinlenme: 45–60 sn',
          ],
        },
        {
          id: 'w4-a-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Easy Bike',
            'Lat Stretch',
            'T-Spine Rotation',
            'Wrist Mobility',
            'Controlled Breathing',
          ],
        },
      ],
    },

    {
      id: 'block-1-week-4-day-b',
      day: 'DAY B',
      title: 'Clean Technique Consolidation',
      duration: '70–80 dk',
      focus: 'Squat Clean · Direct Catch · Strict Pull-up · Front Squat · KB/DB Engine',
      purpose:
        'Power Clean + Front Squat alışkanlığını kırmak, bar altına hızlı girmek, Clean bar yolunu dikleştirmek, Strict Pull-up tam ROM geliştirmek ve Front Squat yorgunluğunu azaltmak.',
      sections: [
        {
          id: 'w4-b-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            '2 tur',
            '250 m Bike veya Row',
            '8 Cossack Squat',
            '10 Band Pull Apart',
            '8 Front Rack Lunge',
            '8 Muscle Clean',
            'Barbell Prep: 5 Tall Clean',
            '5 Front Squat',
          ],
        },
        {
          id: 'w4-b-olympic-drill',
          title: 'Olympic Drill',
          duration: '12 dk',
          items: [
            'Tall Clean — 3×3 @ 30–40 kg',
            'High-Hang Squat Clean — 3×2 @ 45–50 kg',
            'Clean High Pull — 3×3 @ 50–55 kg',
            'Dinlenme: 60–75 sn',
            'Tall Clean: Barı yükseltmeye çalışma.',
            'Tall Clean: Kendini barın altına çek.',
            'High-Hang Squat Clean: Direkt Squat Catch.',
            'Power Catch → Squat yasak.',
            'Clean High Pull: Bar vücuda yakın.',
            'Clean High Pull: Kalçayla barı ileri vurma.',
            'Clean High Pull: Dikey bar yolu.',
          ],
        },
        {
          id: 'w4-b-olympic-lift',
          title: 'Olympic Lift — Squat Clean',
          items: [
            'Squat Clean — 5×2 @ %70–72.5 / 62.5–65 kg',
            'RPE: 6–6.5',
            'Dinlenme: 2 dk',
            'Ana kural: Direkt Squat Clean.',
            'Takip: 10 tekrarın kaçı direkt Squat Catch?',
            'Hedef: En az 8/10 direkt Squat Catch.',
            'Power Clean + Front Squat teknik başarılı tekrar sayılmayacak.',
            'Video: Mümkünse son 2 set.',
          ],
        },
        {
          id: 'w4-b-gymnastics',
          title: 'Gymnastics — Strict Pull-up',
          items: [
            '5 set: 5 / 4 / 3 / 2 / 1',
            'Toplam: 15 tekrar',
            'Dinlenme: 90 sn',
            'Her tekrar: Tam Dead Hang.',
            'Her tekrar: Tam ROM.',
            'Her tekrar: Çene barı geçecek.',
            'Her tekrar: Kontrollü iniş.',
            'Kural: ROM bozuluyorsa hedef tekrar için zorlama.',
          ],
        },
        {
          id: 'w4-b-strength',
          title: 'Strength — Front Squat',
          items: [
            'Front Squat — 3×4 @ %65 / 67.5–70 kg',
            'RPE: 6–6.5',
            'Dinlenme: 2 dk',
            'İlk 2 tekrar normal.',
            'Son 2 tekrar: 2 sn dip pause.',
            'Odak: Dirsekler yüksek, göğüs dik, core aktif.',
            'Odak: Dipten kontrollü ama agresif çıkış.',
          ],
        },
        {
          id: 'w4-b-metcon',
          title: 'Metcon — KB + DB Engine',
          duration: '10 dk AMRAP',
          items: [
            '10 KB Swing @ 24 kg',
            '8 Alternating DB Hang Clean @ 22.5 kg — 4 sağ + 4 sol',
            '10/8 Cal BikeErg',
            'Hedef RPE: 7',
            'Amaç: Hip extension, unilateral yük kontrolü, grip, DB/KB cycling ve hızlı toparlanma.',
            'Pacing: İlk 2 tur kontrollü.',
            'Pacing: Orta bölüm aynı pace.',
            'Pacing: Son 2 dk RPE ≤7.5 ise tempo artır.',
            'Failure yok.',
            'Teknik bozuluyorsa set kırılabilir.',
          ],
        },
        {
          id: 'w4-b-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '2 tur',
            '8 Bulgarian Split Squat / bacak',
            '12 Ring Row',
            '12 Band External Rotation',
            '30 sn Farmer Hold',
            'Dinlenme: 45–60 sn',
          ],
        },
        {
          id: 'w4-b-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Easy Bike',
            'Front Rack Stretch',
            'Hip Stretch',
            'T-Spine Rotation',
            'Controlled Breathing',
          ],
        },
      ],
    },

    {
      id: 'block-1-week-4-day-c',
      day: 'DAY C',
      title: 'Jerk Quality + Aerobic Competition',
      duration: '70–80 dk',
      focus: 'Split Jerk · Butterfly Under Light Fatigue · Push Press · Aerobic Mixed Modal',
      purpose:
        'Week 3 overhead pressing yorgunluğunu azaltmak, Split Jerk tekniğini korumak, Butterfly’ı hafif yorgunluk altında kullanmak ve competition engine ile pace kontrolünü geliştirmek.',
      sections: [
        {
          id: 'w4-c-warm-up',
          title: 'Warm-up',
          duration: '10 dk',
          items: [
            '2 tur',
            '250 m Row',
            '10 Walking Lunge',
            '10 Scap Push-up',
            '10 Band Pull Apart',
            '8 Empty Bar Push Press',
            '5 Split Jerk Footwork',
          ],
        },
        {
          id: 'w4-c-olympic-drill',
          title: 'Olympic Drill',
          items: [
            'Jerk Balance — 3×3 @ 35–40 kg',
            'Tall Jerk — 3×2 @ 35–40 kg',
            'Dinlenme: 60–75 sn',
            'Odak: Dikey dip.',
            'Odak: Güçlü drive.',
            'Odak: Hızlı lockout.',
            'Odak: Dengeli split.',
            'Odak: Kontrollü recovery.',
          ],
        },
        {
          id: 'w4-c-olympic-lift',
          title: 'Olympic Lift — Split Jerk',
          items: [
            'Split Jerk — 5×2 @ %70 / 55–57.5 kg',
            'RPE: 6–6.5',
            'Dinlenme: 2 dk',
            'Video: Mümkünse son 2 set.',
            'Odak: Bar öne kaçmayacak.',
            'Odak: Ön ve arka ayak dengesi korunacak.',
            'Odak: Lockout agresif olacak.',
          ],
        },
        {
          id: 'w4-c-gymnastics',
          title: 'Gymnastics — Butterfly Under Light Fatigue',
          items: [
            '4 set',
            '8 Butterfly Pull-up',
            'Hemen ardından 8/6 Cal Row',
            'Dinlenme: 75 sn',
            'Amaç: Butterfly’ı kontrollü kardiyovasküler yorgunlukla birleştirmek.',
            'Odak: Push-away, baş nötr, ayaklar bitişik, hollow korunacak.',
            'Odak: Son tekrar ilk tekrar gibi.',
            'Not: Bu bir metcon değil.',
            'Row performansı önemsiz.',
            'Butterfly kalitesi öncelikli.',
          ],
        },
        {
          id: 'w4-c-strength',
          title: 'Strength — Push Press',
          items: [
            'Push Press — 3×5 @ %60–65 / 45–47.5 kg',
            'RPE: 6–6.5',
            'Dinlenme: 2 dk',
            'Amaç: Week 3 pressing yorgunluğunu toparlamak.',
            'Odak: Hızlı bar, dikey dip, güçlü leg drive, temiz lockout.',
            'Kural: Grind yok.',
            'RPE 7 üzerine çıkıyorsa kilo azalt.',
          ],
        },
        {
          id: 'w4-c-metcon',
          title: 'Metcon — Aerobic Mixed Modal',
          duration: '15 dk AMRAP',
          items: [
            '200 m Run',
            '10 Wall Ball @ 9 kg',
            '8 Toes-to-Bar',
            '6 Single DB Front Rack Walking Lunge @ 22.5 kg — 3 sağ + 3 sol',
            '8/6 Cal Row',
            'Hedef RPE: 7–7.5',
            'Pacing 0–5 dk: Kontrollü.',
            'Pacing 5–10 dk: Aynı pace.',
            'Pacing 10–15 dk: İyi hissediyorsan artır.',
            'Ana hedef: İlk 5 dakika ile son 5 dakika arasında büyük pace çöküşü olmayacak.',
          ],
        },
        {
          id: 'w4-c-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '2 tur',
            '10 GHD Sit-up',
            '10 Single Arm DB Bench Press / kol @ 17.5 kg',
            '12 Face Pull',
            'Dinlenme: 45–60 sn',
          ],
        },
        {
          id: 'w4-c-cool-down',
          title: 'Cool Down',
          items: [
            '5 dk Easy Walk veya Bike',
            'Lat Stretch',
            'Hip Flexor Stretch',
            'T-Spine',
            'Controlled Breathing',
          ],
        },
      ],
    },

    {
      id: 'block-1-week-4-day-d',
      day: 'DAY D',
      title: 'Home Athletic Development / Recovery',
      duration: '50–60 dk',
      focus: 'Double Under · Strict Pull-up · RDL · Unilateral Strength · Zone 2',
      purpose:
        'Opsiyonel toparlanma ve athletic development günü. Day A-B-C sonrasında toparlanma iyi değilse yapılmayacak ve ana günlerin recovery’sini bozmayacak.',
      sections: [
        {
          id: 'w4-d-warm-up',
          title: 'Warm-up',
          duration: '8 dk',
          items: [
            '3 tur',
            '10 Air Squat',
            '8 Push-up',
            '8 Empty Bar RDL',
            '20 sn Dead Hang',
          ],
        },
        {
          id: 'w4-d-skill',
          title: 'Skill — Double Under',
          duration: '10 dk',
          items: [
            'Amaç: Bilekten çevirme.',
            'Amaç: Küçük sıçrama.',
            'Amaç: Sabit ritim.',
            'Amaç: Rahat nefes.',
            'Çalışma: Single → Single-Single-Double → Kısa Double Under bağlantıları.',
            'Failure yok.',
            'Yüksek nabız yok.',
          ],
        },
        {
          id: 'w4-d-gymnastics',
          title: 'Gymnastics — Strict Pull-up',
          items: [
            'Strict Pull-up — 4×3',
            'Tam Dead Hang',
            'Tam ROM',
            'Dinlenme: 90 sn',
            'RPE: 6',
          ],
        },
        {
          id: 'w4-d-strength',
          title: 'Strength — Romanian Deadlift',
          items: [
            'Romanian Deadlift — 3×6 @ %65–70 / 75–80 kg',
            'RPE: 6–7',
            'Dinlenme: 2 dk',
            'Tempo: 31X1',
          ],
        },
        {
          id: 'w4-d-unilateral',
          title: 'Unilateral Strength',
          items: [
            '3 tur',
            '8 Single Leg RDL / bacak — 1×17.5 kg DB',
            '8 Single Arm DB Bench Press / kol — 17.5 kg',
            '8 Reverse Lunge / bacak — 1×17.5 kg DB',
            'Dinlenme: 60–90 sn',
          ],
        },
        {
          id: 'w4-d-conditioning',
          title: 'Conditioning — Zone 2',
          duration: '20–25 dk',
          items: [
            'Zone 2',
            'Evde uygun cardio ekipmanı yoksa kolay koşu veya yürüyüş + koşu kombinasyonu.',
            'Hedef: Konuşabilecek tempo.',
            'RPE: 4–5',
            'Bu bölüm yarışma conditioning’i değil.',
            'Recovery + aerobic base.',
          ],
        },
        {
          id: 'w4-d-accessory',
          title: 'Accessory — Opsiyonel',
          items: [
            '2 tur',
            '15 Hollow Body Rock',
            '20 sn Dead Hang',
            '10 Scap Pull-up',
          ],
        },
        {
          id: 'w4-d-cool-down',
          title: 'Cool Down',
          duration: '5 dk',
          items: [
            'Hamstring Stretch',
            'Hip Stretch',
            'Lat Stretch',
            'T-Spine',
            'Controlled Breathing',
          ],
        },
      ],
    },
  ],
};

export default block1Week4;
